### ISSUE TITLE
simple upload/visualise/knock screencast

### ISSUE THREAD

**Issue by hredestig** [DD-DeCaF/scrum#1]

**Comment by hredestig** [comment]
- make slides
  - [X] happy examples slide
  - [X] 'too complicated' slide
  - [X] screenshot eu page slide
  - [X] we mostly produce ethanol by fermentation using yeast, but what would ethanol producing e coli look like?
  - [X] csv files
- audio
  - [X] find music
  - [X] write script
  - [X] source voice
- record
  - [ ] uploading csv files
  - [ ] click look max yield (seems there is room for improvement?)
  - [ ] switch to pathway try to knock something
  - [ ] switch to iloop
- edit

**Comment by phantomas1234** [comment]
Use recording lab at DTU@library
