### ISSUE TITLE
Meta card: organize workshop materials for Delft

### ISSUE THREAD

**Issue by Midnighter** [DD-DeCaF/scrum#149]
In organizing the workshop for ICSB, we realized a couple of shortcomings that we would like to address before Delft:

* [x] Have the jupyterhub setup files tracked in a repository (possibly having branches/separate clones for each workshop).
* [x] The jupyterhub repo should pull in the workshop materials via git subtree so that they can easily be updated to the latest version.
* [x] We should offer multiple forms of authentication (Google, GitHub, BitBucket plus LDAP for internal users when it makes sense). (no, multiple is difficult, github is a better option)
* [ ] We should build our own specific images rather than relying on the conda-based scipy-jupyter image.
* [x] Re-evaluate alpine-python as a base image for our modelling services and the jupyter server.
* [ ] Setup guidelines should be written down in the `README` and possibly be published on our blog.
* [x] Depersonalise authentication
* [ ] add CarveME
* [ ] add eggnog-mapper

**Comment by sgalkina** [comment]
invite Daniel to the review
