### ISSUE TITLE
Some yeast user feedback

### ISSUE THREAD

**Issue by Midnighter** [DD-DeCaF/scrum#158]
* Many reactions on the interactive map are marked as not present in the model. This is sometimes due to identifier problems, for example, `PSCVTi` on the map and `PSCVT` in `iMM904`.
* The label text is quite small compared to the arrow sizes. They also overlap quite often.
* Should reactions in the model with no confidence score or annotated GPR be not considered for pathway prediction?
* It would be very useful to have gene or protein labels of the organism rather than BiGG IDs on the map.

**Comment by phantomas1234** [comment]
- [ ] _Many reactions on the interactive map are marked as not present in the model. This is sometimes due to identifier problems, for example, PSCVTi on the map and PSCVT in iMM904._ To be solved in https://github.com/DD-DeCaF/metabolica-ui-map/issues/13
- [ ] _The label text is quite small compared to the arrow sizes. They also overlap quite often.
Should reactions in the model with no confidence score or annotated GPR be not considered for pathway prediction?_ I am not sure I understand this one.
- [ ] _It would be very useful to have gene or protein labels of the organism rather than BiGG IDs on the map._ To be fixed in https://github.com/DD-DeCaF/metabolica-ui-map/issues/96

**Comment by Midnighter** [comment]
> Should reactions in the model with no confidence score or annotated GPR be not considered for pathway prediction?

Pathway prediction is based on the universal model, when assessing multiple potential heterologous pathways it would be helpful to easily inspect the individual reactions' evidence (annotations, experimental, literature). A user might prefer reactions with known genes in other organisms rather than putative reactions.

The confidence score might be a nice statistic to show for the reactions in the pathway. Or I could prune the universal model beforehand by dropping reactions below a certain confidence score. I would tend towards the former.
