### ISSUE TITLE
As a user I want to be able to use dd-decaf back-end services so I can develop my own tailored application

### ISSUE THREAD

**Issue by hredestig** [DD-DeCaF/scrum#17]
- [ ] learn what interfaces customers find most important. e.g. insilico life
- [ ] show use of backend services in jupyter notebook (e.g. wrapped in camilo)
- [ ] possibly add certain services to kbase app store https://narrative.kbase.us/#appcatalog
