### ISSUE TITLE
As a user I want to manage my sequences and sequence annotations in the decaf platform

### ISSUE THREAD

**Issue by hredestig** [DD-DeCaF/scrum#27]
stakeholder: iloop stakeholders / po

- [ ] ice live and working, 
- [ ] user can click on gnomic elements and get redirected to ice
- [ ] complete melatonin pathway
