### ISSUE TITLE
As a user I want to be able to generate a sorted list of strain designs based on varying amounts of information

### ISSUE THREAD

**Issue by phantomas1234** [DD-DeCaF/scrum#81]
Putting this into DD-DeCaF/scrum but this should probably get its own service repo at some point.

Done when (MVP):
- [ ] User can select product (mandatory), host organism (optional), carbon source (optional)
- [ ] User can submit a potentially long running job
- [ ] User is presented with a table of strain designs

Bonus:
- [ ] User gets notified when job is done (email, webhook, Atom, ...)
- [ ] Jobs utilize parallelization
- [ ] Sharing enabled with pathway visualization app
